name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering

# ref: https://github.com/clemlesne/blue-agent/blob/main/.github/workflows/pipeline.yaml
env:
  CONTAINER_NAME: ${{ github.repository }}
  CONTAINER_REGISTRY_GHCR: ghcr.io
  CONTAINER_REGISTRY_DOCKER_HUB: docker.io
  # https://github.com/sigstore/cosign/releases
  COSIGN_VERSION: 2.4.1
  # https://npmjs.com/package/@microsoft/sarif-multitool?activeTab=versions
  SARIF_MULTITOOL_VERSION: 4.5.4
  # https://npmjs.com/package/snyk?activeTab=versions
  SNYK_VERSION: 1.1294.3
  # https://github.com/microsoft/azure-pipelines-agent/releases
  AZP_AGENT_VERSION: 4.248.0
  # https://github.com/PowerShell/PowerShell/releases
  POWERSHELL_VERSION: 7.2.24
  # https://github.com/krallin/tini/releases
  TINI_VERSION: 0.19.0
  # https://github.com/mikefarah/yq/releases
  YQ_VERSION: 4.44.6
  # https://go.dev/dl
  GO_VERSION: 1.23.4
  # https://github.com/rootless-containers/rootlesskit/releases
  ROOTLESSKIT_VERSION: 2.3.1
  # https://github.com/moby/buildkit/releases
  BUILDKIT_VERSION: 0.18.2
  # https://github.com/Azure/azure-cli/releases
  AZURE_CLI_VERSION: 2.67.0
  # https://github.com/stedolan/jq/releases
  JQ_WIN_VERSION: 1.7.1
  # https://github.com/aws/aws-cli/tags
  AWS_CLI_VERSION: 2.22.29
  # https://console.cloud.google.com/artifacts/docker/google.com:cloudsdktool/us/gcr.io/google-cloud-cli
  # Note: To get thhe version number, spot the version tag on the latest pushed container
  GCLOUD_CLI_VERSION: 497.0.0
  # https://github.com/git-for-windows/git/releases
  GIT_WIN_VERSION: 2.47.1
  # https://github.com/facebook/zstd/releases
  ZSTD_WIN_VERSION: 1.5.6
  # https://www.python.org/downloads
  PYTHON_VERSION_MAJOR_MINOR: 3.12
  PYTHON_VERSION_PATCH: 8
  # https://nodejs.org/en/download/releases
  NODE_VERSION: 22.12.0
  # https://github.com/helm/helm/releases
  HELM_VERSION: 3.16.4
  # https://github.com/oras-project/oras/releases
  ORAS_VERSION: 1.2.0
  # https://github.com/docker/buildx/releases
  BUILDX_VERSION: 0.19.3
  # https://github.com/hadolint/hadolint/releases
  HADOLINT_VERSION: 2.12.0
  # https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history#fixed-version-bootstrappers
  VS_BUILDTOOLS_WIN_VERSION: f2819554-a618-400d-bced-774bb5379965/cc7231dc668ec1fb92f694c66b5d67cba1a9e21127a6e0b31c190f772bd442f2
  # https://github.com/gohugoio/hugo/releases
  HUGO_VERSION: 0.140.2
  # See: https://github.com/getsops/sops/releases
  SOPS_VERSION: 3.9.3
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: "ubuntu-basic"
            dockerfile: "Dockerfile.ubuntu.basic"
            arch: linux/amd64
          - name: "bookworm"
            dockerfile: "Dockerfile.bookworm"
            arch: linux/amd64


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build Docker Image
      #   run: |
      #     docker build -t ghcr.io/stewartshea/ado-agent:${{ matrix.image.name }}-latest . -f ${{ matrix.image.dockerfile }}

      # - name: Push Docker Image
      #   run: |
      #     docker push ghcr.io/stewartshea/ado-agent:${{ matrix.image.name }}-latest
      - name: Build & push container
        uses: docker/build-push-action@v6.10.0
        with:
          build-args: |
            AWS_CLI_VERSION=${{ env.AWS_CLI_VERSION }}
            AZP_AGENT_VERSION=${{ env.AZP_AGENT_VERSION }}
            AZURE_CLI_VERSION=${{ env.AZURE_CLI_VERSION }}
            BUILDKIT_VERSION=${{ env.BUILDKIT_VERSION }}
            GCLOUD_CLI_VERSION=${{ env.GCLOUD_CLI_VERSION }}
            GO_VERSION=${{ env.GO_VERSION }}
            POWERSHELL_VERSION=${{ env.POWERSHELL_VERSION }}
            PYTHON_VERSION_MAJOR_MINOR=${{ env.PYTHON_VERSION_MAJOR_MINOR }}
            PYTHON_VERSION_PATCH=${{ env.PYTHON_VERSION_PATCH }}
            ROOTLESSKIT_VERSION=${{ env.ROOTLESSKIT_VERSION }}
            TINI_VERSION=${{ env.TINI_VERSION }}
            YQ_VERSION=${{ env.YQ_VERSION }}
          context: .
          file: ${{ matrix.image.dockerfile }}
          outputs: type=registry,oci-mediatypes=true,compression=estargz,compression-level=9,force-compression=true
          platforms: ${{ matrix.image.arch }}
          tags: ${{ matrix.image.name }}-latest